######################## GNU General Public License 3.0 ########################
##                                                                            ##
## Copyright (C) 2023 Kevin Matthes                                           ##
##                                                                            ##
## This program is free software: you can redistribute it and/or modify       ##
## it under the terms of the GNU General Public License as published by       ##
## the Free Software Foundation, either version 3 of the License, or          ##
## (at your option) any later version.                                        ##
##                                                                            ##
## This program is distributed in the hope that it will be useful,            ##
## but WITHOUT ANY WARRANTY; without even the implied warranty of             ##
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the              ##
## GNU General Public License for more details.                               ##
##                                                                            ##
## You should have received a copy of the GNU General Public License          ##
## along with this program.  If not, see <https://www.gnu.org/licenses/>.     ##
##                                                                            ##
################################################################################

################################################################################
##
##  AUTHOR      Kevin Matthes
##  BRIEF       A GitHub Action to create a blank Scriv fragment.
##  COPYRIGHT   GPL-3.0
##  DATE        2023
##  FILE        action.yml
##  NOTE        See `LICENSE' for full license.
##              See `README.md' for project details.
##
################################################################################

# The icon with which this Action is presented in the Marketplace.
branding:
  color: green
  icon: book

# About this Action.
author: 'https://github.com/kevinmatthes'
description: A GitHub Action to create a blank Scriv fragment.
name: create-scriv-fragment

# The actual behaviour of this Action.
runs:
  using: composite
  steps:
    - name: Prepare the Python 3 environment.
      uses: actions/setup-python@v5.4.0
      with:
        python-version: 3.11

    - name: Create the list of Python 3 software requirements.
      run: echo scriv >> create-scriv-fragment.requirements.txt
      shell: bash

    - name: Install the Python 3 software requirements.
      uses: py-actions/py-dependency-install@v4.1.0
      with:
        path: create-scriv-fragment.requirements.txt

    - name: Remove the list of Python 3 software requirements.
      run: rm create-scriv-fragment.requirements.txt
      shell: bash

    - name: Configure the user creating the fragment.
      uses: fregante/setup-git-user@v2.0.2

    - name: Create the fragment.
      run: |
        scriv create --add \
        && git commit -m \
               "`git config --list \
                 | grep user\.name \
                 | cut -d= -f2`:  Create fresh Scriv fragment"
      shell: bash

################################################################################
